FROM resin/%%BALENA_MACHINE_NAME%%-debian

RUN apt-get update && \
	apt-get install -yq build-essential python3-dev python3 python3-setuptools python3-pip && \
	apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip3 install wiringpi jsonrpclib-pelix

WORKDIR /usr/src/app

COPY . ./

ENV INITSYSTEM on

CMD ["bash", "start.sh"]

